# Use the Python 3.11 base image
FROM rocky8-python311

# Image arguments
ARG APP_NAME=pycli
ENV APP_NAME=${APP_NAME}

# Set the working directory
WORKDIR /app

# Install PyInstaller
RUN pip3 install --no-cache-dir wheel pyinstaller

# Copy entrypoint script and application code
COPY entrypoint-build.sh ./
RUN chmod +x ./entrypoint-build.sh
COPY pyproject.toml ./
COPY src/ ./src/

# Run PyInstaller to build the executable
CMD ["sh", "-c", "./entrypoint-build.sh \"$APP_NAME\""]
